<?php

/**
 * Implements hook_theme().
 */
function hyperspot_core_theme($existing, $type, $theme, $path) {
  return array(
    'my_settings' => array(
      'variables' => array(
        'items' => array(),
      )
    ),
    'my_profile_edit' => array(
      'render element' => 'form',
    ),
    'my_profile_edit_user_picture' => array(
      'render element' => 'element',
    ),
    'my_reservation_edit' => array(
      'render element' => 'form',
    ),
  );
}
